parameters:
  host: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.host }}
  pool: ${{ parameters.pool }}
  steps:
  - ${{ if eq(parameters.host, 'macOS') }}:
    - script: brew install pkg-config
      displayName: 'Install pkg-config (for testing)'
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: 'npm install -g esy@latest --unsafe-perm'
      displayName: 'Installing deps'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: 'sudo npm install -g esy@latest --unsafe-perm'
      displayName: 'Installing deps'
  - script: esy i
    displayName: 'esy i'
  - ${{ if eq(parameters.host, 'Windows') }}:
    - script: esy b bash .ci/pkg-config-cygwin.sh
      displayName: 'Installing pkg-config in cygwin'
  - script: esy x pkg-config --libs libffi
    displayName: 'Build and Dry run'
